version: 2

project_name: kartoza-geoserver-client

before:
  hooks:
    - go mod tidy

builds:
  - id: kartoza-geoserver-client
    binary: kartoza-geoserver-client
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - SPECIFICATION.md

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kartoza
    name: kartoza-geoserver-client
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Kartoza GeoServer Client {{ .Version }}

    A Midnight Commander-style TUI for managing GeoServer instances.

    ### Highlights

    - **Dual-panel interface** - Local filesystem on the left, GeoServer explorer on the right
    - **Multi-connection support** - Manage multiple GeoServer instances simultaneously
    - **Upload with verification** - Upload Shapefiles, GeoPackage, GeoTIFF with automatic verification
    - **Full CRUD operations** - Create, edit, delete workspaces, stores, and layers
    - **Layer preview** - Built-in MapLibre GL web viewer with WMS support
    - **Vim-style navigation** - Familiar j/k/h/l keys for navigation

  footer: |
    ---

    ### Installation

    #### Quick Install (Linux/macOS)
    ```bash
    # Download and extract
    curl -sSL https://github.com/kartoza/kartoza-geoserver-client/releases/download/{{ .Tag }}/kartoza-geoserver-client_{{ .Version }}_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/').tar.gz | tar xz

    # Move to PATH
    sudo mv kartoza-geoserver-client /usr/local/bin/
    ```

    #### Debian/Ubuntu
    ```bash
    sudo dpkg -i kartoza-geoserver-client_{{ .Version }}_amd64.deb
    ```

    #### Fedora/RHEL
    ```bash
    sudo rpm -i kartoza-geoserver-client-{{ .Version }}.x86_64.rpm
    ```

    ---

    ### Nix Installation

    #### Run directly (no install)
    ```bash
    nix run github:kartoza/kartoza-geoserver-client
    ```

    #### Install to profile
    ```bash
    nix profile install github:kartoza/kartoza-geoserver-client
    ```

    #### Add to flake.nix
    ```nix
    {
      inputs = {
        nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
        kartoza-geoserver-client.url = "github:kartoza/kartoza-geoserver-client";
      };

      outputs = { self, nixpkgs, kartoza-geoserver-client, ... }: {
        # Option 1: Use the overlay
        nixosConfigurations.myhost = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          modules = [
            ({ pkgs, ... }: {
              nixpkgs.overlays = [ kartoza-geoserver-client.overlays.default ];
              environment.systemPackages = [ pkgs.kartoza-geoserver-client ];
            })
          ];
        };

        # Option 2: Reference package directly
        # environment.systemPackages = [ kartoza-geoserver-client.packages.x86_64-linux.default ];
      };
    }
    ```

    #### Add to configuration.nix (non-flake)
    ```nix
    { config, pkgs, ... }:
    let
      kartoza-geoserver-client = (builtins.getFlake "github:kartoza/kartoza-geoserver-client").packages.${pkgs.system}.default;
    in
    {
      environment.systemPackages = [ kartoza-geoserver-client ];
    }
    ```

    #### Add to home-manager
    ```nix
    { pkgs, ... }:
    let
      kartoza-geoserver-client = (builtins.getFlake "github:kartoza/kartoza-geoserver-client").packages.${pkgs.system}.default;
    in
    {
      home.packages = [ kartoza-geoserver-client ];
    }
    ```

    ---

    ### Quick Start

    1. Launch: `kartoza-geoserver-client`
    2. Press `c` to open connection manager
    3. Press `a` to add a GeoServer connection
    4. Navigate and explore!

    **Made with love by [Kartoza](https://kartoza.com)**

nfpms:
  - id: packages
    package_name: kartoza-geoserver-client
    vendor: Kartoza
    homepage: https://github.com/kartoza/kartoza-geoserver-client
    maintainer: Tim Sutton <tim@kartoza.com>
    description: "A Midnight Commander-style TUI for managing GeoServer instances"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: README.md
        dst: /usr/share/doc/kartoza-geoserver-client/README.md
      - src: LICENSE
        dst: /usr/share/doc/kartoza-geoserver-client/LICENSE
