version: 2

project_name: kartoza-cloudbench

before:
  hooks:
    - go mod tidy

builds:
  # TUI application
  - id: kartoza-cloudbench
    binary: kartoza-cloudbench
    main: .
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

  # Web application (requires frontend to be pre-built)
  - id: kartoza-cloudbench-web
    binary: kartoza-cloudbench-web
    main: ./cmd/web
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}

archives:
  # TUI archive
  - id: tui
    builds:
      - kartoza-cloudbench
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - SPECIFICATION.md

  # Web archive
  - id: web
    builds:
      - kartoza-cloudbench-web
    format: tar.gz
    name_template: >-
      kartoza-cloudbench-web_
      {{- .Version }}_
      {{- .Os }}_
      {{- .Arch }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

snapshot:
  version_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

release:
  github:
    owner: kartoza
    name: kartoza-cloudbench
  draft: false
  prerelease: auto
  mode: replace
  header: |
    ## Kartoza Cloud Workbench {{ .Version }}

    A Midnight Commander-style TUI and modern Web interface for managing geospatial cloud infrastructure.

    ### Available Packages

    This release includes two applications:

    - **kartoza-cloudbench** - Terminal UI (TUI) with dual-panel interface
    - **kartoza-cloudbench-web** - Web interface with React-based UI

    ### Highlights

    - **Dual-panel TUI** - Local filesystem on the left, cloud services explorer on the right
    - **Modern Web UI** - React-based interface with Chakra UI
    - **Multi-service support** - Manage GeoServer, PostgreSQL/PostGIS, S3 storage, Apache Iceberg, QFieldCloud
    - **Upload with verification** - Upload Shapefiles, GeoPackage, GeoTIFF with automatic verification
    - **Full CRUD operations** - Create, edit, delete workspaces, stores, and layers
    - **Layer preview** - Built-in MapLibre GL web viewer with WMS support
    - **Comprehensive metadata editing** - Edit layer title, abstract, keywords, attribution
    - **Vim-style navigation** - Familiar j/k/h/l keys for navigation (TUI)

  footer: |
    ---

    ### Installation

    #### TUI - Quick Install (Linux/macOS)
    ```bash
    # Download and extract
    curl -sSL https://github.com/kartoza/kartoza-cloudbench/releases/download/{{ .Tag }}/kartoza-cloudbench_{{ .Version }}_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/').tar.gz | tar xz

    # Move to PATH
    sudo mv kartoza-cloudbench /usr/local/bin/
    ```

    #### Web UI - Quick Install (Linux/macOS)
    ```bash
    # Download and extract
    curl -sSL https://github.com/kartoza/kartoza-cloudbench/releases/download/{{ .Tag }}/kartoza-cloudbench-web_{{ .Version }}_$(uname -s | tr '[:upper:]' '[:lower:]')_$(uname -m | sed 's/x86_64/amd64/').tar.gz | tar xz

    # Move to PATH
    sudo mv kartoza-cloudbench-web /usr/local/bin/

    # Run on port 8080 (default)
    kartoza-cloudbench-web
    # Or specify a different port
    kartoza-cloudbench-web -addr :3000
    ```

    #### Debian/Ubuntu - TUI
    ```bash
    sudo dpkg -i kartoza-cloudbench_{{ .Version }}_amd64.deb
    ```

    #### Debian/Ubuntu - Web UI
    ```bash
    sudo dpkg -i kartoza-cloudbench-web_{{ .Version }}_amd64.deb
    ```

    #### Fedora/RHEL - TUI
    ```bash
    sudo rpm -i kartoza-cloudbench-{{ .Version }}.x86_64.rpm
    ```

    #### Fedora/RHEL - Web UI
    ```bash
    sudo rpm -i kartoza-cloudbench-web-{{ .Version }}.x86_64.rpm
    ```

    ---

    ### Nix Installation

    #### Run TUI directly (no install)
    ```bash
    nix run github:kartoza/kartoza-cloudbench
    ```

    #### Run Web UI directly (no install)
    ```bash
    nix run github:kartoza/kartoza-cloudbench#web
    ```

    #### Install to profile
    ```bash
    # TUI
    nix profile install github:kartoza/kartoza-cloudbench

    # Web UI
    nix profile install github:kartoza/kartoza-cloudbench#kartoza-cloudbench-web
    ```

    #### Add to flake.nix
    ```nix
    {
      inputs = {
        nixpkgs.url = "github:NixOS/nixpkgs/nixos-unstable";
        kartoza-cloudbench.url = "github:kartoza/kartoza-cloudbench";
      };

      outputs = { self, nixpkgs, kartoza-cloudbench, ... }: {
        # Option 1: Use the overlay
        nixosConfigurations.myhost = nixpkgs.lib.nixosSystem {
          system = "x86_64-linux";
          modules = [
            ({ pkgs, ... }: {
              nixpkgs.overlays = [ kartoza-cloudbench.overlays.default ];
              environment.systemPackages = [
                pkgs.kartoza-cloudbench      # TUI
                pkgs.kartoza-cloudbench-web  # Web UI
              ];
            })
          ];
        };

        # Option 2: Reference package directly
        # environment.systemPackages = [
        #   kartoza-cloudbench.packages.x86_64-linux.default
        #   kartoza-cloudbench.packages.x86_64-linux.kartoza-cloudbench-web
        # ];
      };
    }
    ```

    #### Add to configuration.nix (non-flake)
    ```nix
    { config, pkgs, ... }:
    let
      kcb = builtins.getFlake "github:kartoza/kartoza-cloudbench";
    in
    {
      environment.systemPackages = [
        kcb.packages.${pkgs.system}.default               # TUI
        kcb.packages.${pkgs.system}.kartoza-cloudbench-web  # Web UI
      ];
    }
    ```

    #### Add to home-manager
    ```nix
    { pkgs, ... }:
    let
      kcb = builtins.getFlake "github:kartoza/kartoza-cloudbench";
    in
    {
      home.packages = [
        kcb.packages.${pkgs.system}.default               # TUI
        kcb.packages.${pkgs.system}.kartoza-cloudbench-web  # Web UI
      ];
    }
    ```

    ---

    ### Quick Start

    #### TUI
    1. Launch: `kartoza-cloudbench`
    2. Press `c` to open connection manager
    3. Press `a` to add a GeoServer connection
    4. Navigate and explore!

    #### Web UI
    1. Launch: `kartoza-cloudbench-web`
    2. Open browser: http://localhost:8080
    3. Click "Add Connection" to add a GeoServer
    4. Browse and manage your geospatial cloud services!

    **Made with love by [Kartoza](https://kartoza.com)**

nfpms:
  # TUI package
  - id: tui-packages
    package_name: kartoza-cloudbench
    builds:
      - kartoza-cloudbench
    vendor: Kartoza
    homepage: https://github.com/kartoza/kartoza-cloudbench
    maintainer: Tim Sutton <tim@kartoza.com>
    description: "A Midnight Commander-style TUI for managing geospatial cloud infrastructure"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: README.md
        dst: /usr/share/doc/kartoza-cloudbench/README.md
      - src: LICENSE
        dst: /usr/share/doc/kartoza-cloudbench/LICENSE

  # Web package
  - id: web-packages
    package_name: kartoza-cloudbench-web
    builds:
      - kartoza-cloudbench-web
    vendor: Kartoza
    homepage: https://github.com/kartoza/kartoza-cloudbench
    maintainer: Tim Sutton <tim@kartoza.com>
    description: "A modern web interface for managing geospatial cloud infrastructure"
    license: MIT
    formats:
      - deb
      - rpm
    bindir: /usr/bin
    contents:
      - src: README.md
        dst: /usr/share/doc/kartoza-cloudbench-web/README.md
      - src: LICENSE
        dst: /usr/share/doc/kartoza-cloudbench-web/LICENSE
